# Generated by Django 5.2.17 on 2026-10-05 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_fiscal_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_of_sale', to='billing.fiscalprofile')),
            ],
            options={
                'db_table': 'billing_points_of_sale',
            },
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.PositiveSmallIntegerField(choices=[(1, 'Factura A'), (6, 'Factura B'), (11, 'Factura C')])),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sequences', to='billing.pointofsale')),
            ],
            options={
                'db_table': 'billing_invoice_sequences',
            },
        ),
        migrations.AddConstraint(
            model_name='pointofsale',
            constraint=models.UniqueConstraint(fields=('fiscal_profile', 'number'), name='unique_point_of_sale_number_per_fiscal_profile'),
        ),
        migrations.AddConstraint(
            model_name='invoicesequence',
            constraint=models.UniqueConstraint(fields=('point_of_sale', 'invoice_type'), name='unique_sequence_per_point_of_sale_and_invoice_type'),
        ),
    ]
