# Generated by Django 5.2.18 on 2026-10-07 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_pointofsale_invoicesequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.PositiveSmallIntegerField(choices=[(1, 'Factura A'), (6, 'Factura B'), (11, 'Factura C')])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued')], default='draft', max_length=20)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('concept', models.PositiveSmallIntegerField(choices=[(1, 'Productos'), (2, 'Servicios'), (3, 'Productos y Servicios')])),
                ('service_date_from', models.DateField(blank=True, null=True)),
                ('service_date_to', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_vat_condition', models.PositiveSmallIntegerField(choices=[(1, 'IVA Responsable Inscripto'), (4, 'IVA Sujeto Exento'), (5, 'Consumidor Final'), (6, 'Responsable Monotributo'), (13, 'Monotributista Social'), (15, 'IVA No Alcanzado'), (16, 'Monotributo Trabajador Independiente Promovido')])),
                ('receiver_document_type', models.PositiveSmallIntegerField(choices=[(80, 'CUIT'), (86, 'CUIL'), (87, 'CDI'), (96, 'DNI')])),
                ('receiver_document_number', models.CharField(max_length=20)),
                ('receiver_address', models.CharField(max_length=255)),
                ('net_taxed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_untaxed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_exempt', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('issuer_legal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('issuer_tax_id', models.CharField(blank=True, max_length=20, null=True)),
                ('issuer_address', models.CharField(blank=True, max_length=255, null=True)),
                ('issuer_vat_condition', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'IVA Responsable Inscripto'), (4, 'IVA Sujeto Exento'), (5, 'Consumidor Final'), (6, 'Responsable Monotributo'), (13, 'Monotributista Social'), (15, 'IVA No Alcanzado'), (16, 'Monotributo Trabajador Independiente Promovido')], null=True)),
                ('issuer_gross_income', models.CharField(blank=True, max_length=30, null=True)),
                ('issuer_activity_start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.pointofsale')),
            ],
            options={
                'db_table': 'billing_invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_treatment', models.CharField(choices=[('taxed', 'Taxed'), ('exempt', 'Exempt'), ('untaxed', 'Untaxed'), ('not_discriminated', 'Not Discriminated')], max_length=20)),
                ('vat_rate', models.PositiveSmallIntegerField(blank=True, choices=[(3, '0%'), (9, '2,5%'), (8, '5%'), (4, '10,5%'), (5, '21%'), (6, '27%')], null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
            options={
                'db_table': 'billing_invoice_items',
                'constraints': [models.CheckConstraint(condition=models.Q(('discount__gte', 0), ('discount__lte', 100)), name='invoice_item_discount_between_0_and_100')],
            },
        ),
    ]
