# Generated by Django 5.2.17 on 2026-08-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('tax_id',), name='unique_company_tax_id'),
        ),
    ]
